export const workflows = [
  {id:'WF-001',slug:'review-prd',name:'Review PRD',category:'Product',description:'Find UX gaps, ambiguous requirements, missing states, and PM questions.',placeholder:'Paste the PRD or product requirement here…',focus:['User journey','Missing states','Error handling','Business rules'],output:'Structured design review',task:'Review the supplied product requirement from a product-design perspective.',objective:'Identify UX gaps, ambiguous requirements, missing states, and unresolved interaction decisions.'},
  {id:'WF-002',slug:'missing-requirements',name:'Find missing requirements',category:'Product',description:'Expose requirements needed before a designer can confidently complete the flow.',placeholder:'Paste the feature brief, PRD, or current requirements…',focus:['Inputs & outputs','States','Permissions','Dependencies'],output:'Prioritized question list',task:'Audit the supplied requirements for missing product and UX requirements.',objective:'Identify information that must be clarified before design or implementation.'},
  {id:'WF-003',slug:'unhappy-paths',name:'Generate unhappy paths',category:'UX',description:'Generate failures, edge cases, recovery paths, and missing UX states.',placeholder:'Paste the happy path, user flow, or feature description…',focus:['User error','System error','Dependency failure','Recovery'],output:'Unhappy-path matrix',task:'Analyze the supplied happy path and generate relevant unhappy paths.',objective:'Identify failure states, edge cases, recovery paths, and missing UX states.'},
  {id:'WF-004',slug:'ux-critique',name:'UX critique',category:'UX',description:'Critique an experience for clarity, usability, consistency, and recoverability.',placeholder:'Describe or paste the current UX, screens, or interaction behavior…',focus:['Clarity','Usability','Consistency','Recovery'],output:'Prioritized UX critique',task:'Critique the supplied user experience as a senior product designer.',objective:'Identify concrete usability risks and improvements without inventing unsupported requirements.'},
  {id:'WF-005',slug:'user-flow',name:'Generate user flow',category:'UX',description:'Translate requirements into actors, steps, decisions, states, and exits.',placeholder:'Paste the feature requirements or desired user outcome…',focus:['Actors','Decision points','States','Exit conditions'],output:'Structured user flow',task:'Translate the supplied requirements into an implementation-ready user flow.',objective:'Make the end-to-end journey, decisions, states, and exceptions explicit.'},
  {id:'WF-006',slug:'prototype',name:'Generate prototype prompt',category:'Prototype',description:'Turn a product brief into a strong prompt for an AI UI/coding tool.',placeholder:'Paste the product brief, user flow, or interface requirements…',focus:['Information architecture','Interactions','States','Responsive behavior'],output:'Prototype-generation prompt',task:'Create an implementation-oriented prototype brief for an AI UI or coding tool.',objective:'Produce enough product, interaction, state, and visual guidance to generate a useful prototype.'},
  {id:'WF-007',slug:'competitor-research',name:'Competitor UX research',category:'Research',description:'Create a structured research plan and comparison framework for competitor UX.',placeholder:'Paste the product area, research question, and competitors if known…',focus:['Journey','Patterns','Friction','Differentiation'],output:'Research plan + comparison matrix',task:'Create a structured competitor UX research plan from the supplied context.',objective:'Define what to inspect, how to compare competitors, and what evidence to capture.'},
  {id:'WF-008',slug:'design-spec',name:'Generate design specification',category:'Documentation',description:'Convert a flow or feature description into a structured design specification.',placeholder:'Paste the approved flow, feature behavior, or design notes…',focus:['Behavior','States','Validation','Handoff questions'],output:'Engineering-ready design spec',task:'Convert the supplied design context into a structured design specification.',objective:'Make expected behavior, states, validation, dependencies, and unresolved questions explicit.'}
];
